on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy,rustfmt

      - run: cargo fmt -- --check

      - run: cargo clippy --workspace --all-targets --all-features -- \
          -D warnings \
          -D clippy::pedantic \
          -D clippy::nursery

      - run: cargo build
